## Using Formula

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df=pd.read_csv("Glucose.csv")
df

Subject  Age  Glucose Level
0        1   43             99
1        2   21             65
2        3   25             79
3        4   42             75
4        5   57             87
5        6   59             81

In [12]:
x=df.iloc[:,1].values
y=df.iloc[:,2].values
print(x)
print(y)

[43 21 25 42 57 59]
[99 65 79 75 87 81]


In [13]:
n=np.size(x)
n

6

In [14]:
sum_x=np.sum(x)
sum_y=np.sum(y)
sum_xy=np.sum(x*y)
sum_x2=np.sum(x**2)
print(sum_x,sum_y,sum_xy,sum_x2)


247 486 20485 11409


In [15]:
m=((n*sum_xy)-(sum_x*sum_y))/((n*sum_x2)-(sum_x)**2)
m

0.3852249832102082

In [16]:
c=((sum_y*sum_x2)-(sum_x*sum_xy))/((n*sum_x2)-(sum_x)**2)
c

65.1415715245131

In [17]:
pred=int(input("Enter the age for which glucose level is predicted:"))
y_pred=m*pred+c
y_pred

Enter the age for which glucose level is predicted:55


86.32894560107455

In [20]:
def LinearRegression(data,val_pred):
    x=data.iloc[:,1].values
    y=data.iloc[:,2].values
    n=np.size(x)
    
    sum_x=np.sum(x)
    sum_y=np.sum(y)
    sum_xy=np.sum(x*y)
    sum_x2=np.sum(x**2)
    
    m=((n*sum_xy)-(sum_x*sum_y))/((n*sum_x2)-(sum_x)**2)
    c=((sum_y*sum_x2)-(sum_x*sum_xy))/((n*sum_x2)-(sum_x)**2)
    
    y_pred=m*val_pred+c
    return y_pred

In [21]:
age=55
glucose_level=LinearRegression(df,age)
print("The glucose level for age",age,"is",glucose_level)

The glucose level for age 55 is 86.32894560107455


## Using sklearn

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [23]:
df=pd.read_csv("Glucose.csv")
df

Subject  Age  Glucose Level
0        1   43             99
1        2   21             65
2        3   25             79
3        4   42             75
4        5   57             87
5        6   59             81

In [24]:
reg = linear_model.LinearRegression()
reg.fit(df.iloc[:,1:2],df.iloc[:,2:3])

LinearRegression()

In [25]:
reg.predict([[55]])

array([[86.3289456]])