## Using Formula

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [21]:
df=pd.read_csv("Glucose.csv")
df

Subject  Age  Glucose Level
0        1   43             99
1        2   21             65
2        3   25             79
3        4   42             75
4        5   57             87
5        6   59             81

In [22]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values
print(x)
print(y)

[1 2 3 4 5 6]
[43 21 25 42 57 59]


In [23]:
n=np.size(x)
n

6

In [24]:
sum_x=np.sum(x)
sum_y=np.sum(y)
sum_xy=np.sum(x*y)
sum_x2=np.sum(x**2)


In [25]:
m=((n*sum_xy)-(sum_x*sum_y))/((n*sum_x2)-(sum_x)**2)
m

5.857142857142857

In [26]:
c=((sum_y*sum_x2)-(sum_x*sum_xy))/((n*sum_x2)-(sum_x)**2)
c

20.666666666666668

In [35]:
pred=int(input("Enter the age for which glucose level is predicted:"))
y_pred=m*pred+c
y_pred

Enter the age for which glucose level is predicted:55


342.8095238095238

In [28]:
def LinearRegression(data,val_pred):
    x=data.iloc[:,0].valuess
    y=data.iloc[:,1].values
    n=np.size(x)
    
    sum_x=np.sum(x)
    sum_y=np.sum(y)
    sum_xy=np.sum(x*y)
    sum_x2=np.sum(x**2)
    
    m=((n*sum_xy)-(sum_x*sum_y))/((n*sum_x2)-(sum_x)**2)
    c=((sum_y*sum_x2)-(sum_x*sum_xy))/((n*sum_x2)-(sum_x)**2)
    
    y_pred=m*val_pred+c
    return y_pred

In [29]:
age=55
glucose_level=LinearRegression(df,age)
print("The glucose level for age",age,"is",glucose_level)

The glucose level for age 55 is 342.8095238095238


## Using sklearn

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [31]:
df=pd.read_csv("Glucose.csv")
df

Subject  Age  Glucose Level
0        1   43             99
1        2   21             65
2        3   25             79
3        4   42             75
4        5   57             87
5        6   59             81

In [43]:
reg = linear_model.LinearRegression()
reg.fit(df.iloc[:,1:2],df.iloc[:,2:3])

LinearRegression()

In [44]:
reg.predict([[55]])

array([[86.3289456]])